---
- name: Push images from managed nodes into dockerhub
  hosts: 172.31.10.186
  tasks:
   - name: Login into dockerhub
     docker_login:
      username: sandytanti
      password: Aix@1234567
      email: sandeepktanti@gmail.com
   - name: Push the customised docker image
     docker_image:
      name: sandytanti/myalpine
      push: yes
      source: local
...

