---
- name: install tomcat9
  hosts: all
  vars:
   - a: tomcat9
   - b: present
   - c: no
  tasks:
   - name: install
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...     
