---
- name: Create ci-cd environment using docker and ansible
  hosts: all
  tasks:
   - name: create jenkins as a container
     docker_container:
      image: "jenkins/jenkins:lts"
      name: devserver
      ports:
       - 5555:8080
   - name: start a tomcat container (qaserver and prodserver)
     docker_container:
      image: tomcat
      name: "{{item.a}}"
      ports:
       - "{{item.b}}"
      links:
       - devserver:jenkins
     with_items:
      - {a: qaserver, b: "6666:8080"}
      - {a: prodserver,b: "7777:8080"}
...        
           
        
