---
- name: implementing loops
  hosts: all
  tasks:
   - name: installing s/w packages
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - apache2
      - maven
...

