---
- name: configuring tomcat9
  hosts: all
  tasks:
   - name: install tomcat9
     apt:
      name: tomcat9
      state: present
   - name: change the port no of tomcat from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: pause for 3 seconds
     pause:
      seconds: 3
   - name: check url response of server1
     uri:
      url: http://172.31.10.186:9090
      status_code: [200]
   - name: check url response of server2
     uri:
      url: http://172.31.0.242:9090
      status_code: [200]
   - name: chechk url response of server3
     uri:
      url: http://172.31.2.161:9090
      status_code: [200]     
...

