---
- name: configuring tomcat9
  hosts: all
  tasks:
   - name: install tomcat9
     apt:
      name: tomcat9
      state: present
   - name: change the port no of tomcat from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9
     service:
      name: tomcat9
      state: restarted
...     

            

