---
- name: working on tomcat container
  hosts: all
  tasks:
   - name: start tomcat as a container
     docker_container:
      image: tomcat
      name: webserver
   - name: stop tomcat container
     docker_container:
      name: webserver
      state: stopped
   - name: Remove the tomcat container
     docker_container:
      name: webserver
      state: absent
...

