---
- name: installing java using host scope variables
  hosts: 172.31.10.186
  tasks:
   - name: install java
     apt: 
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...     
